// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousDriveToScore.h"
#include "Subsystems/Arm.h"
#include "Subsystems/Chassis.h"
#include "Subsystems/Elevator.h"
#include "Subsystems/ElevatorPID.h"
#include "Subsystems/Intake.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

//Added for sendable chooser for autonomous commands
#include "Commands/AutonomousPickupAndScore.h"
#include "Commands/AutonomousPickupCanAndScore.h"
#include "Commands/AutonomousPickupThreeTotesAndScore.h"
#include "Commands/AutonomousPickupTwoTotesAndScore.h"
#include "Commands/AutonomousKnockOverCan.h"
#include "Commands/AutonomousTesting.h"

class Robot : public IterativeRobot {
public:
	Command *autonomousCommand;
	static OI *oi;
	LiveWindow *lw;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static Chassis* chassis;
	static Elevator* elevator;
	static Arm* arm;
	static ElevatorPID* elevatorPID;
	static Intake* intake;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestPeriodic();

	//Variables for implementation of sendable choosers in SmartDashboard
	SendableChooser *chooser;
};
#endif
