// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutonomousPickupTwoTotesAndScore.h"
#include "ChassisDriveStraightForTime.h"
#include "ChassisDriveStraightForDistance.h"
#include "ChassisRotate.h"
#include "ElevatorGotoPosition.h"
#include "ArmCalibrate.h"
#include "ElevatorAutoZero.h"
#include "IntakeCalibrate.h"
#include "IntakeOpen.h"
#include "IntakeClose.h"
#include "IntakeOut.h"
#include "IntakeIn.h"
#include "IntakeSpin.h"
#include "IntakeSpinRight.h"
#include "ArmOpen.h"
#include "ArmClose.h"

#define	TOTE_RAISE_POSITION		1800.0f			// raise totes above can height
#define TOTE_DRIVE_POSITION      531.0f			// safe height to travel with
#define TOTE_STACK_POSITION      831.0f			// Height to move tote stack above a tote on floow
#define V_KNOCK_CAN		0.45f
#define V_COLLECT_TOTE	0.4f
#define V_FULL 1.0f
#define D_CAN 48.0f			// distance to move to end of rectangle
#define D_TOTE 33.0f		// distance from end of rectangle to next tote
#define D_SCORE 80.0f		// distance from rectangle to center of scoring zone
#define T_INTAKE_MOVE 0.500f		// time for intake to open/close
#define T_INTAKE_IN 0.500f	// time to pull tote with intake spinning
#define T_ARM 0.500f		// time for arm to open/close
#define T_SPIN_RT 2.0f		// time to run spin motors to push can

AutonomousPickupTwoTotesAndScore::AutonomousPickupTwoTotesAndScore() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.

	AddSequential(new ArmOpen());									// open arms to pass around tote
	AddSequential(new IntakeOpen());							// opens intake
	AddSequential(new WaitCommand(T_ARM));							// wait for arm to open
	AddSequential(new ElevatorAutoZero());							// lower elevator
	AddSequential(new ArmClose());									// grab first tote
	AddSequential(new WaitCommand(T_ARM));							// wait for arm to close
	AddSequential(new ElevatorGotoPosition(TOTE_RAISE_POSITION));	// raise tote

	// Whack can #1 on way to tote #2
	AddSequential(new IntakeClose());								// close intake
	AddSequential(new WaitCommand(T_INTAKE_MOVE));

	//the following two commands happen in parallel (intake opens while moving too)
	AddParallel(new IntakeSpinRight(), T_SPIN_RT);				    // spin intake away from robot
	AddSequential(new ChassisDriveStraightForDistance(D_CAN, V_KNOCK_CAN, true));	// move to next tote
	AddSequential(new IntakeOpen());								// open intake
	AddSequential(new ChassisDriveStraightForDistance(D_TOTE, V_COLLECT_TOTE, false));	// approach 2nd tote

	AddSequential(new IntakeClose());									// close intake to pull in bin
	AddSequential(new IntakeIn(), T_INTAKE_IN);						// spin inward to pull tote

	AddSequential(new IntakeOpen());								// open intake
	AddSequential(new WaitCommand(T_INTAKE_MOVE));
	AddSequential(new ElevatorGotoPosition(0.0));					// lower elevator to grab bottom
	AddSequential(new ElevatorGotoPosition(TOTE_DRIVE_POSITION));	// raise stack of 2 totes

	// go to autonomous scoring zone
	AddSequential(new ChassisRotate(90.0));
	AddSequential(new WaitCommand(0.250));
	AddSequential(new ChassisRotate(90.0, true));
	AddSequential(new ChassisDriveStraightForTime(3.3));
	AddSequential(new ElevatorGotoPosition(0.0));
	AddSequential(new ArmOpen());

}
