// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CHASSISPIDDRIVESTRAIGHTFORDISTANCE_H
#define CHASSISPIDDRIVESTRAIGHTFORDISTANCE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "../SimplePIDOutput.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ChassisPIDDriveStraightForDistance: public Command {
private:
	double mDistance = 0.0F;
	PIDController *drive = NULL;
	SimplePIDOutput *distance = NULL;
	unsigned int OnTargetCount = 0;

public:
	ChassisPIDDriveStraightForDistance();
	ChassisPIDDriveStraightForDistance(double distance);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
