// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ChassisDriveStraightForDistance.h"

#define COAST_DISTANCE 10.0F

ChassisDriveStraightForDistance::ChassisDriveStraightForDistance() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ChassisDriveStraightForDistance::Initialize() {
	Robot::chassis->ResetChassisYaw();
	Robot::chassis->ResetChassisDistance();
}

// Called repeatedly when this Command is scheduled to run
void ChassisDriveStraightForDistance::Execute() {
	if (fabs(mDistance) - fabs(Robot::chassis->ReadChassisDistance()) < COAST_DISTANCE) {
		Robot::chassis->DriveStraight(mCoastMagnitude);
	}
	else {
		Robot::chassis->DriveStraight(mMagnitude);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ChassisDriveStraightForDistance::IsFinished() {
	return (fabs(Robot::chassis->ReadChassisDistance()) >= fabs(mDistance));
}

// Called once after isFinished returns true
void ChassisDriveStraightForDistance::End() {
	Robot::chassis->StopMotors();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChassisDriveStraightForDistance::Interrupted() {

}

ChassisDriveStraightForDistance::ChassisDriveStraightForDistance(double distance,
		float magnitude) {
	Requires(Robot::chassis);
	mDistance = distance;
	mMagnitude = magnitude;
	mCoastMagnitude = magnitude / 3.0f;
}
