// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ElevatorGotoPosition.h"

ElevatorGotoPosition::ElevatorGotoPosition() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_commandTargetPosition = 0;  // Just in case our overloaded constructor is not invoked or someone clicks this internal command from Smart Dashboard
}

ElevatorGotoPosition::ElevatorGotoPosition(float TargetPosition) {
	Requires(Robot::elevator);
	m_commandTargetPosition = TargetPosition;
}

// Called just before this Command runs the first time
void ElevatorGotoPosition::Initialize() {
	Robot::elevator->StartMovingTowardTargetPosition(m_commandTargetPosition);	// Tell elevator subsystem to start moving toward command-invoker-requested target position
}

// Called repeatedly when this Command is scheduled to run
void ElevatorGotoPosition::Execute() {
	Robot::elevator->AccelerateMaxSpeedDecelerate();		// Tell elevator subsystem to speed up; stay constant; slow down,  based on current distance from start or finish
}

// Make this return true when this Command no longer needs to run execute()
bool ElevatorGotoPosition::IsFinished() {
	return Robot::elevator->ReachedTargetPosition();
}

// Called once after isFinished returns true
void ElevatorGotoPosition::End() {
	Robot::elevator->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevatorGotoPosition::Interrupted() {
	End();
}
