// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ElevatorGotoPositionWithPower.h"

ElevatorGotoPositionWithPower::ElevatorGotoPositionWithPower() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_commandTargetPosition = 0;  // Just in case our overloaded constructor is not invoked or someone clicks this internal command from Smart Dashboard
	m_commandMotorPower = 0;  // Just in case our overloaded constructor is not invoked or someone clicks this internal command from Smart Dashboard
}

ElevatorGotoPositionWithPower::ElevatorGotoPositionWithPower(float TargetPosition, float MotorPower) {
	Requires(Robot::elevator);
	m_commandTargetPosition = TargetPosition;
	m_commandMotorPower = MotorPower;
}

// Called just before this Command runs the first time
void ElevatorGotoPositionWithPower::Initialize() {
	Robot::elevator->StartMovingTowardTargetPositionWithPower(m_commandTargetPosition, m_commandMotorPower);	// Tell elevator subsystem to start moving toward command-invoker-requested target position
}

// Called repeatedly when this Command is scheduled to run
void ElevatorGotoPositionWithPower::Execute() {
	Robot::elevator->AccelerateMaxSpeedDecelerateWithPower(m_commandMotorPower);		// Tell elevator subsystem to speed up; stay constant; slow down,  based on current distance from start or finish
}

// Make this return true when this Command no longer needs to run execute()
bool ElevatorGotoPositionWithPower::IsFinished() {
	return Robot::elevator->ReachedTargetPosition();
}

// Called once after isFinished returns true
void ElevatorGotoPositionWithPower::End() {
	Robot::elevator->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevatorGotoPositionWithPower::Interrupted() {
	End();

}
