// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "ElevatorFloorStage.h"
#include "ElevatorGotoPosition.h"

ElevatorFloorStage::ElevatorFloorStage() {

	// Move Arm to tote level 2, plus 2" clearance to allow driving over totes on the floor
	AddSequential(new ElevatorGotoPosition( 831 ));	// Initial estimate 1416
}
